### PR TITLE
for vector recycling warning 

### PR DESCRIPTION
**Pull request by jread-usgs**

### CODE REVIEW

**Comment by lawinslow** [comment]
Thanks @jread-usgs 
Could you fix the line endings? The change record doesn't show up well due to a line ending change.

**Comment by jread-usgs** [comment]
whoops. that's a mess.

**Comment by jread-usgs** [comment]
Should be good now. I would like to keep those indents in the schmidt function, but realize it creates a big diff w/ no functional change.

**Comment by lawinslow** [comment]
Looks good! Now to fix travis....

**Pull request merged**
